apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: terraform-segment-data-lakes
  description: Terraform module for Segment Data Lakes
spec:
  type: library
  lifecycle: production
  owner: group:default/sup-org-2930 # https://backstage.twilioinfra.com/catalog/default/group/sup-org-2930
