agents:
  queue: general-039

env:
  ECR_REGISTRY: 018537234677.dkr.ecr.us-east-1.amazonaws.com

steps:
  - label: ":lint-roller: Linted"
    plugins:
      - docker#v5.12.0:
          image: ${ECR_REGISTRY}/docker.io/hashicorp/terraform:1.15.5
          command: ["fmt", "-check", "-recursive", "-diff"]
